name: Ping Render Every 1 Minutes

on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl ping to keep site awake
        run: echo "Pinging at $(date)" && curl -s --max-time 120 https://www.kirananalyst.com/ || echo "Ping failed"
